name: automerge

on:
  # Try enabling auto-merge for all open pull requests on branches starting with 'webui/' prefix
  push:
    branches:
      - 'webui/**'

  # Try enabling auto-merge for a pull request when branch starts with "webui/", when
  # a pull request is updated in any way (opened, synchronized, reopened, edited).
  pull_request_target:
    branches:
      - 'webui/**'
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  automerge:
    name: Auto-Merge Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: no-merge
          pull-request: ${{ github.event.inputs.pull-request }}